### ISSUE TITLE
Release 8.10.0 breaks python 2.7 compatibility with Redis instrumentation

### ISSUE THREAD

**Issue by gleme** [newrelic/newrelic-python-agent#1236]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

**Description**
I recently tried updating python's new relic agent for a legacy application that still uses python 2.7 with redis 2.10.5 and I'm having the following error:
<img width="1723" alt="image" src="https://github.com/user-attachments/assets/84967ee6-6ca9-4884-80ee-97810e79e741">

**Expected Behavior**
Instrumentation for redis on python 2.7 should work, or at least there should be a breaking change note on the release notes, or move the python 2.7 deprecation warning to version 8.10.0, as it is on version 10 in the current release notes docs.

**Steps to Reproduce**
- Install new relic agent on a python 2.7.18 environment with redis-py version 2.10
- Start the agent on an application (in our case Flask)
- You should see syntax errors related to coroutines using `async` python 3 keyword

**Your Environment**
Python 2.7.18 - pip 20.3.4 - Ubuntu 22.04.5 LTS
Flask 1.1.1
Redis 2.10.5

**Comment by hmstepanek** [comment]
It looks like between version 8.9 and 8.10 we dropped support for redis 3 and consequently Python2.7 since redis 4 and above do not support Python2.7. I do not see anything in the release notes about this though so I'll fix that. The version of redis you are using is very old and we dropped support for it way before v8.9. It's hard for me to tell exactly when since it pre-dates a lot of our testing infrastructure but it looks like support was dropped around mid 2021. Note just because we drop support doesn't necessarily mean the new agent version won't work with it. When we drop support for a particular library version, it just means we no longer test against that version so the agent at some point in the future may stop working with that library version.

**Comment by gleme** [comment]
> It looks like between version 8.9 and 8.10 we dropped support for redis 3 and consequently Python2.7 since redis 4 and above do not support Python2.7. I do not see anything in the release notes about this though so I'll fix that. The version of redis you are using is very old and we dropped support for it way before v8.9. It's hard for me to tell exactly when since it pre-dates a lot of our testing infrastructure but it looks like support was dropped around mid 2021. Note just because we drop support doesn't necessarily mean the new agent version won't work with it. When we drop support for a particular library version, it just means we no longer test against that version so the agent at some point in the future may stop working with that library version.

Thanks for clarifying that! It makes sense, we are on our way to migrate all python 2.7 code, it will just take some time, I will try updating redis for the latest supported python 2.7 version for now and let you know my results later, hopefully version [3.5.3](https://github.com/redis/redis-py/releases/tag/3.5.3) works, their release docs prior to 4.0.0 version are hard to figure out what were the changes.

**Comment by hmstepanek** [comment]
I'm going to close this issue now but feel free to comment back here if you have any issues with your redis upgrade!
