### ISSUE TITLE
DeprecationWarning: `formatargspec` is deprecated since Python 3.5

### ISSUE THREAD

**Issue by austinbutler** [newrelic/newrelic-python-agent#22]
**Description**

```
.venv/lib/python3.8/site-packages/newrelic/console.py:84: 18 warnings
  /opt/.venv/lib/python3.8/site-packages/newrelic/console.py:84: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
    prototype = wrapper.__name__[3:] + ' ' + inspect.formatargspec(
```

**Expected Behavior**

No deprecation warning.

**Your Environment**

Python 3.8.5, New Relic agent 5.20.0.149.

**Comment by austinbutler** [comment]
🙅

**Comment by qbnut** [comment]
This deprecation warning is still occurring with the latest version 5.22.1.152, with target project as Python 3.7

`../../root/.local/share/virtualenvs/src-x3FbBUl6/lib/python3.7/site-packages/newrelic/console.py:85: 18 warnings
  /root/.local/share/virtualenvs/src-x3FbBUl6/lib/python3.7/site-packages/newrelic/console.py:85: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
    args[1:], varargs, keywords, defaults)`

**Comment by jacinda** [comment]
Can confirm this is also an issue for projects I work on.  I often run our tests with -Wa to catch deprecation warnings and having this still be open in newrelic is causing extra noise.

**Comment by mwgamble** [comment]
Please re-open this. This issue was not stale and needs attention from the maintainers.

**Comment by Thargelion** [comment]
For future reference, this issue is fixed by newrelic: https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes/python-agent-60402159/

Version: 6.4.2.159
