### ISSUE TITLE
Starlette/FastAPI transactions are inaccessible when using synchronous routes.

### ISSUE THREAD

**Issue by danielapsmaior** [newrelic/newrelic-python-agent#24]
I was using version `5.18.0.148` and this was working fine:

```
@app.get('/')
def index():
    newrelic.agent.ignore_transaction(flag=True)
    return 'Hello World!'
```
By updating to `5.20.0.149`, it started showing up in New Relic dashboard.
Tested in `5.20.1.150` and the bug persists.

Using Uvicorn / FastAPI, Python 3.8.
```
newrelic-admin run-program uvicorn server:app
```

**Comment by a-feld** [comment]
Hi @danielapsmaior , thanks for filing this issue! I believe this is related to a known issue with the agent's monitoring of starlette/fastapi that the team is currently working on (#5)!

### TL/DR
The agent doesn't see any transaction running when `newrelic.agent.ignore_transaction()` is called and therefore, there is no transaction to be ignored. To work around this problem while we address it in the agent code (next release), one of the following should be done:

* Disable uvicorn instrumentation by adding the following to your `newrelic.ini`:
    ```
    [import-hook:uvicorn.config]
    enabled=false
    ```
* Change the signature of `def index` to `async def index`

Could you also confirm if removing `newrelic.agent.ignore_transaction` still results in the transaction being missing on `5.18.0.148`?

### Details
The background is related to how the agent internally tracks the "current transaction" or "current trace/segment". The implementation for this tracking is in [trace_cache.py](https://github.com/newrelic/newrelic-python-agent/blob/d41fb461e7a4eb428fa85b0abc21734814bd7390/newrelic/core/trace_cache.py).

The agent's data structures around timing, error tracking, etc. are not considered thread safe. The agent is designed so that once a transaction is started on a particular thread, it tracks the transaction only within that thread. This design limitation (until addressed) means that any time a transaction crosses a thread boundary, no additional details / tracking of the transaction can be done on the new thread.

So, what's the deal here, and how is the above relevant? Well, [starlette runs all non-coroutine routes on a separate thread](https://github.com/encode/starlette/blob/b3271a53b0b5c98ef3117dc0b82bd7f700fb44a8/starlette/routing.py#L43) and so does [fastapi](https://github.com/tiangolo/fastapi/blob/e77ea635777d2494690ba3eb62bd005b9edeefde/fastapi/routing.py#L135). That currently means that any non-async routes lose the "current transaction" anywhere it is needed. Timing information is still accurate, but details will be omitted.

I suspect that the call to `newrelic.agent.ignore_transaction()` didn't actually work in `5.18.0.148` either. Before `5.20.0`, the agent didn't include automatic instrumentation for `uvicorn`, so a transaction must have been started manually. What likely happened is the transaction wasn't started for the function being "ignored", so it gave the perception that the ignore call was actually working. 😄

**Comment by danielapsmaior** [comment]
@a-feld Thank you for your answer!

I confirm that putting `async` in all signatures worked! And also that removing `newrelic.agent.ignore_transaction` from `5.18.0.148` still keeps ignoring transaction!

Thank you again and I'm very excited with the agent support to FastAPI :🌟

**Comment by a-feld** [comment]
@danielapsmaior We've released starlette / FastAPI support, so this issue should be resolved! 🎉
