### ISSUE TITLE
Errors after upgrade to 7.x

### ISSUE THREAD

**Issue by daveisfera** [newrelic/newrelic-python-agent#468]
**Description**
Data appears to be reported by both but this error is output with 7.x:
```
(1/ThreadPoolExecutor-0_0) newrelic.core.context ERROR - Runtime instrumentation error. Request context propagation failed. No trace with id 139977538623376. Report this issue to New Relic support.
```

**Expected Behavior**
7.x would work like 6.x

**Steps to Reproduce**
Run `channels` with a `django` project

**Your Environment**
django 2.2.26 and channels 3.0.4

**Additional context**
Had to add this to get the instrumentation working at all:
https://discuss.newrelic.com/t/cannot-get-new-relic-to-run-with-heroku-django-gunicorn-asgi-uvicorn/93061

**Comment by TimPansino** [comment]
Hello,

This is a new log message that was put in place to identify some existing issues, there shouldn't be an actual change in behavior since it was introduced. 

Can you confirm that you're seeing this log message after update to `v7.4.0.172`? There was a fix included in that to remove this log message erroneously getting reported in asgiref instrumentation, it affected django notably.

Also, there is instrumentation out of the box now for asgi, uvicorn, and your django version, do you still need to manually add instrumentation to see data with `channels`? That shouldn't be necessary as far as I'm aware.

**Comment by daveisfera** [comment]
Updating to `v7.4.0.172` fixed the error logs, but without the manual instrumentation mentioned in that link, no data makes it to New Relic.

Here's the versions of modules that we're currently using:
```
asgiref==3.4.1
channels==3.0.4 
daphne==3.0.2 
django==2.2.26
```

**Comment by daveisfera** [comment]
This is still an issue and it would be nice if it were fixed to not require this manual instrumentation.

**Comment by TimPansino** [comment]
@daveisfera you appear to be using daphne as your webserver which is an unsupported framework, which would be why you don't see any data. You could try using uvicorn or submitting a feature request for daphne.
